import { describe, expect, test } from "bun:test";

import { parseCargoLockText } from "../src/graph/rust-cargo-lock";

describe("parseCargoLockText", () => {
  test("parses direct, development, and transitive Cargo dependencies", () => {
    const cargoLock = [
      "# This file is automatically @generated by Cargo.",
      "",
      "[[package]]",
      "name = \"aho-corasick\"",
      "version = \"1.1.3\"",
      "source = \"registry+https://github.com/rust-lang/crates.io-index\"",
      "",
      "[[package]]",
      "name = \"dev-risk\"",
      "version = \"0.1.0\"",
      "source = \"registry+https://github.com/rust-lang/crates.io-index\"",
      "",
      "[[package]]",
      "name = \"regex\"",
      "version = \"1.10.4\"",
      "source = \"registry+https://github.com/rust-lang/crates.io-index\"",
      "dependencies = [",
      " \"aho-corasick 1.1.3\",",
      "]"
    ].join("\n");
    const cargoToml = [
      "[package]",
      "name = \"fixture-rust\"",
      "version = \"0.1.0\"",
      "",
      "[dependencies]",
      "regex = \"1\"",
      "",
      "[dev-dependencies]",
      "dev-risk = \"0.1\""
    ].join("\n");

    const result = parseCargoLockText(cargoLock, "fixture-rust/Cargo.lock", {
      manifestText: cargoToml
    });

    expect(result.ok).toBe(true);
    if (!result.ok) {
      throw new Error(result.error.message);
    }

    expect(result.value.rootName).toBe("fixture-rust");
    expect(result.value.nodes.map((node) => node.id)).toEqual([
      "aho-corasick@1.1.3",
      "dev-risk@0.1.0",
      "regex@1.10.4"
    ]);
    expect(result.value.nodes.find((node) => node.id === "regex@1.10.4"))
      .toMatchObject({
        ecosystem: "cargo",
        dependencyType: "production",
        direct: true,
        paths: [["fixture-rust", "regex@1.10.4"]]
      });
    expect(result.value.nodes.find((node) => node.id === "aho-corasick@1.1.3"))
      .toMatchObject({
        ecosystem: "cargo",
        dependencyType: "production",
        direct: false,
        paths: [["fixture-rust", "regex@1.10.4", "aho-corasick@1.1.3"]]
      });
    expect(result.value.nodes.find((node) => node.id === "dev-risk@0.1.0"))
      .toMatchObject({
        ecosystem: "cargo",
        dependencyType: "development",
        direct: true,
        paths: [["fixture-rust", "dev-risk@0.1.0"]]
      });
  });

  test("uses package aliases from Cargo.toml when resolving lockfile records", () => {
    const result = parseCargoLockText(
      [
        "[[package]]",
        "name = \"actual-crate\"",
        "version = \"1.0.0\""
      ].join("\n"),
      "Cargo.lock",
      {
        manifestText: [
          "[package]",
          "name = \"fixture-rust\"",
          "",
          "[dependencies]",
          "alias_crate = { package = \"actual-crate\", version = \"1\" }"
        ].join("\n")
      }
    );

    expect(result.ok).toBe(true);
    if (!result.ok) {
      throw new Error(result.error.message);
    }

    expect(result.value.nodes.map((node) => node.id)).toEqual(["actual-crate@1.0.0"]);
    expect(result.value.nodes[0]?.direct).toBe(true);
  });

  test("uses root lockfile dependency versions when the same crate appears more than once", () => {
    const cargoLock = [
      "[[package]]",
      "name = \"fixture-rust\"",
      "version = \"0.1.0\"",
      "dependencies = [",
      " \"shared-crate 2.0.0\",",
      "]",
      "",
      "[[package]]",
      "name = \"shared-crate\"",
      "version = \"1.0.0\"",
      "",
      "[[package]]",
      "name = \"shared-crate\"",
      "version = \"2.0.0\""
    ].join("\n");
    const cargoToml = [
      "[package]",
      "name = \"fixture-rust\"",
      "version = \"0.1.0\"",
      "",
      "[dependencies]",
      "shared-crate = \"2\""
    ].join("\n");

    const result = parseCargoLockText(cargoLock, "fixture-rust/Cargo.lock", {
      manifestText: cargoToml
    });

    expect(result.ok).toBe(true);
    if (!result.ok) {
      throw new Error(result.error.message);
    }

    expect(result.value.nodes.map((node) => node.id)).toEqual(["shared-crate@2.0.0"]);
    expect(result.value.nodes[0]?.paths).toEqual([["fixture-rust", "shared-crate@2.0.0"]]);
  });

  test("reports malformed package records as typed errors", () => {
    const result = parseCargoLockText(
      [
        "[[package]]",
        "name = \"missing-version\""
      ].join("\n"),
      "Cargo.lock"
    );

    expect(result.ok).toBe(false);
    if (result.ok) {
      throw new Error("Expected malformed Cargo.lock to fail.");
    }

    expect(result.error.code).toBe("CARGO_LOCK_PARSE_FAILED");
  });
});
