import { describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

import {
  findCargoWorkspaceMemberManifestPathsFromRelativePaths,
  parseCargoLockfile,
  parseCargoLockText
} from "../src/graph/rust-cargo-lock";

describe("parseCargoLockText", () => {
  test("parses direct, development, and transitive Cargo dependencies", () => {
    const cargoLock = [
      "# This file is automatically @generated by Cargo.",
      "",
      "[[package]]",
      "name = \"aho-corasick\"",
      "version = \"1.1.3\"",
      "source = \"registry+https://github.com/rust-lang/crates.io-index\"",
      "",
      "[[package]]",
      "name = \"dev-risk\"",
      "version = \"0.1.0\"",
      "source = \"registry+https://github.com/rust-lang/crates.io-index\"",
      "",
      "[[package]]",
      "name = \"regex\"",
      "version = \"1.10.4\"",
      "source = \"registry+https://github.com/rust-lang/crates.io-index\"",
      "checksum = \"000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f\"",
      "dependencies = [",
      " \"aho-corasick 1.1.3\",",
      "]"
    ].join("\n");
    const cargoToml = [
      "[package]",
      "name = \"fixture-rust\"",
      "version = \"0.1.0\"",
      "",
      "[dependencies]",
      "regex = \"1\"",
      "",
      "[dev-dependencies]",
      "dev-risk = \"0.1\""
    ].join("\n");

    const result = parseCargoLockText(cargoLock, "fixture-rust/Cargo.lock", {
      manifestText: cargoToml
    });

    expect(result.ok).toBe(true);
    if (!result.ok) {
      throw new Error(result.error.message);
    }

    expect(result.value.rootName).toBe("fixture-rust");
    expect(result.value.nodes.map((node) => node.id)).toEqual([
      "aho-corasick@1.1.3",
      "dev-risk@0.1.0",
      "regex@1.10.4"
    ]);
    expect(result.value.nodes.find((node) => node.id === "regex@1.10.4"))
      .toMatchObject({
        ecosystem: "cargo",
        integrity: "sha256-AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8=",
        dependencyType: "production",
        direct: true,
        paths: [["fixture-rust", "regex@1.10.4"]]
      });
    expect(result.value.nodes.find((node) => node.id === "aho-corasick@1.1.3"))
      .toMatchObject({
        ecosystem: "cargo",
        dependencyType: "production",
        direct: false,
        paths: [["fixture-rust", "regex@1.10.4", "aho-corasick@1.1.3"]]
      });
    expect(result.value.nodes.find((node) => node.id === "dev-risk@0.1.0"))
      .toMatchObject({
        ecosystem: "cargo",
        dependencyType: "development",
        direct: true,
        paths: [["fixture-rust", "dev-risk@0.1.0"]]
      });
  });

  test("stops walking dependency cycles without dropping reachable paths", () => {
    const cargoLock = [
      "[[package]]",
      "name = \"child\"",
      "version = \"2.0.0\"",
      "dependencies = [",
      " \"parent 1.0.0\",",
      "]",
      "",
      "[[package]]",
      "name = \"parent\"",
      "version = \"1.0.0\"",
      "dependencies = [",
      " \"child 2.0.0\",",
      "]"
    ].join("\n");
    const cargoToml = [
      "[package]",
      "name = \"fixture-rust-cycle\"",
      "version = \"0.1.0\"",
      "",
      "[dependencies]",
      "parent = \"1\""
    ].join("\n");

    const result = parseCargoLockText(cargoLock, "fixture-rust-cycle/Cargo.lock", {
      manifestText: cargoToml
    });

    expect(result.ok).toBe(true);
    if (!result.ok) {
      throw new Error(result.error.message);
    }

    expect(result.value.nodes.find((node) => node.id === "parent@1.0.0"))
      .toMatchObject({
        dependencyType: "production",
        direct: true,
        paths: [["fixture-rust-cycle", "parent@1.0.0"]]
      });
    expect(result.value.nodes.find((node) => node.id === "child@2.0.0"))
      .toMatchObject({
        dependencyType: "production",
        direct: false,
        paths: [["fixture-rust-cycle", "parent@1.0.0", "child@2.0.0"]]
      });
  });

  test("bounds dependency path fan-out while retaining every reachable crate", () => {
    const layerCount = 10;
    const packageRecords: string[] = [];
    for (let layer = 0; layer < layerCount; layer += 1) {
      for (const branch of ["a", "b"]) {
        const dependencies = layer === layerCount - 1
          ? ["leaf 1.0.0"]
          : [`layer-${layer + 1}-a 1.0.0`, `layer-${layer + 1}-b 1.0.0`];
        packageRecords.push(
          "[[package]]",
          `name = "layer-${layer}-${branch}"`,
          "version = \"1.0.0\"",
          "dependencies = [",
          ...dependencies.map((dependency) => ` \"${dependency}\",`),
          "]",
          ""
        );
      }
    }
    packageRecords.push(
      "[[package]]",
      "name = \"leaf\"",
      "version = \"1.0.0\""
    );

    const result = parseCargoLockText(
      packageRecords.join("\n"),
      "bounded-cargo/Cargo.lock",
      {
        manifestText: [
          "[package]",
          "name = \"bounded-cargo\"",
          "version = \"0.1.0\"",
          "",
          "[dependencies]",
          "layer-0-a = \"1\"",
          "layer-0-b = \"1\""
        ].join("\n")
      }
    );

    expect(result.ok).toBe(true);
    if (!result.ok) {
      throw new Error(result.error.message);
    }

    expect(result.value.nodes).toHaveLength((layerCount * 2) + 1);
    expect(result.value.nodes.find((node) => node.id === "leaf@1.0.0")?.paths)
      .toHaveLength(64);
    expect(result.value.diagnostics).toEqual([{
      code: "dependency_paths_truncated",
      affectedNodeCount: 7,
      limit: 64,
      message: "Cargo dependency paths were limited."
    }]);
  });

  test("uses Cargo workspace member manifests as dependency roots", () => {
    const cargoLock = [
      "[[package]]",
      "name = \"dev-tool\"",
      "version = \"2.0.0\"",
      "",
      "[[package]]",
      "name = \"prod-child\"",
      "version = \"0.1.0\"",
      "",
      "[[package]]",
      "name = \"prod-root\"",
      "version = \"1.0.0\"",
      "dependencies = [",
      " \"prod-child 0.1.0\",",
      "]",
      "",
      "[[package]]",
      "name = \"actual-workspace\"",
      "version = \"4.0.0\"",
      "",
      "[[package]]",
      "name = \"workspace-shared\"",
      "version = \"3.0.0\""
    ].join("\n");

    const result = parseCargoLockText(cargoLock, "workspace/Cargo.lock", {
      manifestText: [
        "[workspace]",
        "members = [\"crates/app\", \"crates/tools\"]",
        "",
        "[workspace.dependencies]",
        "renamed-workspace = { package = \"actual-workspace\", version = \"4\" }",
        "workspace-shared = \"3\""
      ].join("\n"),
      memberManifestTexts: [
        [
          "[package]",
          "name = \"app\"",
          "version = \"0.1.0\"",
          "",
          "[dependencies]",
          "prod-root = \"1\"",
          "renamed-workspace.workspace = true",
          "workspace-shared.workspace = true"
        ].join("\n"),
        [
          "[package]",
          "name = \"tools\"",
          "version = \"0.1.0\"",
          "",
          "[dev-dependencies]",
          "dev-tool = \"2\""
        ].join("\n")
      ]
    });

    expect(result.ok).toBe(true);
    if (!result.ok) {
      throw new Error(result.error.message);
    }

    expect(result.value.nodes.map((node) => node.id)).toEqual([
      "actual-workspace@4.0.0",
      "dev-tool@2.0.0",
      "prod-child@0.1.0",
      "prod-root@1.0.0",
      "workspace-shared@3.0.0"
    ]);
    expect(result.value.nodes.find((node) => node.id === "prod-root@1.0.0"))
      .toMatchObject({
        dependencyType: "production",
        direct: true
      });
    expect(result.value.nodes.find((node) => node.id === "prod-child@0.1.0"))
      .toMatchObject({
        dependencyType: "production",
        direct: false
      });
    expect(result.value.nodes.find((node) => node.id === "dev-tool@2.0.0"))
      .toMatchObject({
        dependencyType: "development",
        direct: true
      });
    expect(result.value.nodes.find((node) => node.id === "workspace-shared@3.0.0"))
      .toMatchObject({
        dependencyType: "production",
        direct: true
      });
    expect(result.value.nodes.find((node) => node.id === "actual-workspace@4.0.0"))
      .toMatchObject({
        dependencyType: "production",
        direct: true
      });
  });

  test("uses Cargo dependency table sections as dependency roots", () => {
    const result = parseCargoLockText(
      [
        "[[package]]",
        "name = \"actual-table\"",
        "version = \"1.0.0\"",
        "",
        "[[package]]",
        "name = \"table-dev\"",
        "version = \"2.0.0\"",
        "",
        "[[package]]",
        "name = \"actual-workspace-table\"",
        "version = \"3.0.0\"",
        "",
        "[[package]]",
        "name = \"optional-table\"",
        "version = \"4.0.0\"",
        "",
        "[[package]]",
        "name = \"workspace-only\"",
        "version = \"2.0.0\""
      ].join("\n"),
      "fixture-rust/Cargo.lock",
      {
        manifestText: [
          "[package]",
          "name = \"fixture-rust\"",
          "version = \"0.1.0\"",
          "",
          "[workspace.dependencies]",
          "workspace-table-alias = { package = \"actual-workspace-table\", version = \"3\" }",
          "",
          "[dependencies.table-alias]",
          "package = \"actual-table\"",
          "version = \"1\"",
          "",
          "[dependencies.workspace-table-alias]",
          "workspace = true",
          "",
          "[dependencies.optional-table]",
          "version = \"4\"",
          "optional = true",
          "",
          "[target.'cfg(unix)'.dev-dependencies.table-dev]",
          "version = \"2\"",
          "",
          "[workspace.dependencies.workspace-only]",
          "version = \"2\""
        ].join("\n")
      }
    );

    expect(result.ok).toBe(true);
    if (!result.ok) {
      throw new Error(result.error.message);
    }

    expect(result.value.nodes.map((node) => node.id)).toEqual([
      "actual-table@1.0.0",
      "actual-workspace-table@3.0.0",
      "optional-table@4.0.0",
      "table-dev@2.0.0"
    ]);
    expect(result.value.nodes.find((node) => node.id === "actual-table@1.0.0"))
      .toMatchObject({
        dependencyType: "production",
        direct: true
      });
    expect(result.value.nodes.find((node) => node.id === "actual-workspace-table@3.0.0"))
      .toMatchObject({
        dependencyType: "production",
        direct: true
      });
    expect(result.value.nodes.find((node) => node.id === "optional-table@4.0.0"))
      .toMatchObject({
        dependencyType: "optional",
        direct: true
      });
    expect(result.value.nodes.find((node) => node.id === "table-dev@2.0.0"))
      .toMatchObject({
        dependencyType: "development",
        direct: true
      });
  });

  test("embeds license metadata for locked Cargo workspace packages", () => {
    const result = parseCargoLockText(
      [
        "[[package]]",
        "name = \"workspace-app\"",
        "version = \"1.0.0\"",
        "dependencies = [\"workspace-lib 2.0.0\"]",
        "",
        "[[package]]",
        "name = \"workspace-lib\"",
        "version = \"2.0.0\""
      ].join("\n"),
      "workspace/Cargo.lock",
      {
        manifestText: [
          "[package]",
          "name = \"workspace-app\"",
          "version = \"1.0.0\"",
          "",
          "[dependencies]",
          "workspace-lib = { version = \"2\", path = \"crates/lib\" }"
        ].join("\n"),
        memberManifestTexts: [[
          "[package]",
          "name = \"workspace-lib\"",
          "version = \"2.0.0\"",
          "license = \"Unlicense OR MIT\""
        ].join("\n")]
      }
    );

    expect(result.ok).toBe(true);
    if (!result.ok) {
      throw new Error(result.error.message);
    }
    expect(result.value.embeddedEvidence).toEqual([{
      packageId: "workspace-lib@2.0.0",
      metadataLicense: "Unlicense OR MIT",
      metadataSource: "workspace Cargo.toml",
      files: [],
      source: "local",
      warnings: []
    }]);
  });

  test("embeds inherited workspace package license metadata", () => {
    const result = parseCargoLockText(
      [
        "[[package]]",
        "name = \"workspace-app\"",
        "version = \"1.0.0\"",
        "dependencies = [\"workspace-lib 2.0.0\"]",
        "",
        "[[package]]",
        "name = \"workspace-lib\"",
        "version = \"2.0.0\""
      ].join("\n"),
      "workspace/Cargo.lock",
      {
        manifestText: [
          "[package]",
          "name = \"workspace-app\"",
          "version = \"1.0.0\"",
          "",
          "[workspace.package]",
          "version = \"2.0.0\"",
          "license = \"MIT\"",
          "",
          "[dependencies]",
          "workspace-lib = { path = \"crates/lib\" }"
        ].join("\n"),
        memberManifestTexts: [[
          "[package]",
          "name = \"workspace-lib\"",
          "version.workspace = true",
          "license.workspace = true"
        ].join("\n")]
      }
    );

    expect(result.ok).toBe(true);
    if (!result.ok) {
      throw new Error(result.error.message);
    }
    expect(result.value.embeddedEvidence).toEqual([{
      packageId: "workspace-lib@2.0.0",
      metadataLicense: "MIT",
      metadataSource: "workspace Cargo.toml",
      files: [],
      source: "local",
      warnings: []
    }]);
  });

  test("embeds an inherited license for a package declared in the workspace root", () => {
    const result = parseCargoLockText(
      [
        "[[package]]",
        "name = \"cargo\"",
        "version = \"0.101.0\""
      ].join("\n"),
      "Cargo.lock",
      {
        manifestText: [
          "[workspace]",
          "members = []",
          "",
          "[workspace.package]",
          "license = \"MIT OR Apache-2.0\"",
          "",
          "[package]",
          "name = \"cargo\"",
          "version = \"0.101.0\"",
          "license.workspace = true"
        ].join("\n")
      }
    );

    expect(result.ok).toBe(true);
    if (!result.ok) {
      throw new Error(result.error.message);
    }
    expect(result.value.embeddedEvidence).toEqual([{
      packageId: "cargo@0.101.0",
      metadataLicense: "MIT OR Apache-2.0",
      metadataSource: "workspace Cargo.toml",
      files: [],
      source: "local",
      warnings: []
    }]);
  });

  test("reads literal Cargo workspace member manifests from disk", () => {
    const projectRoot = mkdtempSync(path.join(tmpdir(), "ohrisk-cargo-workspace-"));
    const appRoot = path.join(projectRoot, "crates", "app");

    try {
      mkdirSync(appRoot, { recursive: true });
      writeFileSync(
        path.join(projectRoot, "Cargo.toml"),
        [
          "[workspace]",
          "members = [",
          "  \"crates/app\",",
          "]"
        ].join("\n"),
        "utf8"
      );
      writeFileSync(
        path.join(appRoot, "Cargo.toml"),
        [
          "[package]",
          "name = \"app\"",
          "version = \"0.1.0\"",
          "",
          "[dependencies]",
          "workspace-risk = \"1\""
        ].join("\n"),
        "utf8"
      );
      writeFileSync(
        path.join(projectRoot, "Cargo.lock"),
        [
          "[[package]]",
          "name = \"workspace-risk\"",
          "version = \"1.0.0\""
        ].join("\n"),
        "utf8"
      );

      const result = parseCargoLockfile(path.join(projectRoot, "Cargo.lock"));

      expect(result.ok).toBe(true);
      if (!result.ok) {
        throw new Error(result.error.message);
      }

      expect(result.value.nodes).toHaveLength(1);
      expect(result.value.nodes[0]).toMatchObject({
        id: "workspace-risk@1.0.0",
        dependencyType: "production",
        direct: true
      });
    } finally {
      rmSync(projectRoot, { recursive: true, force: true });
    }
  });

  test("uses workspace-root legal files for a contained member without a package license field", () => {
    const projectRoot = mkdtempSync(path.join(tmpdir(), "ohrisk-cargo-root-license-"));
    const memberRoot = path.join(projectRoot, "watt");

    try {
      mkdirSync(memberRoot, { recursive: true });
      writeFileSync(
        path.join(projectRoot, "Cargo.toml"),
        [
          "[workspace]",
          "members = [\"watt\"]",
          "",
          "[workspace.package]",
          "version = \"1.4.0\"",
          "license = \"MPL-2.0\""
        ].join("\n"),
        "utf8"
      );
      writeFileSync(
        path.join(memberRoot, "Cargo.toml"),
        [
          "[package]",
          "name = \"watt\"",
          "version.workspace = true"
        ].join("\n"),
        "utf8"
      );
      writeFileSync(path.join(projectRoot, "LICENSE"), "Mozilla Public License Version 2.0", "utf8");
      writeFileSync(
        path.join(projectRoot, "Cargo.lock"),
        [
          "[[package]]",
          "name = \"watt\"",
          "version = \"1.4.0\""
        ].join("\n"),
        "utf8"
      );

      const result = parseCargoLockfile(path.join(projectRoot, "Cargo.lock"));

      expect(result.ok).toBe(true);
      if (!result.ok) {
        throw new Error(result.error.message);
      }
      expect(result.value.embeddedEvidence).toEqual([{
        packageId: "watt@1.4.0",
        files: [{
          path: "LICENSE",
          kind: "license",
          text: "Mozilla Public License Version 2.0"
        }],
        source: "local",
        warnings: []
      }]);
    } finally {
      rmSync(projectRoot, { recursive: true, force: true });
    }
  });

  test("prefers a contained member legal file over the workspace-root fallback", () => {
    const projectRoot = mkdtempSync(path.join(tmpdir(), "ohrisk-cargo-member-license-"));
    const memberRoot = path.join(projectRoot, "crates", "member");

    try {
      mkdirSync(memberRoot, { recursive: true });
      writeFileSync(
        path.join(projectRoot, "Cargo.toml"),
        [
          "[workspace]",
          "members = [\"crates/member\"]"
        ].join("\n"),
        "utf8"
      );
      writeFileSync(
        path.join(memberRoot, "Cargo.toml"),
        [
          "[package]",
          "name = \"member\"",
          "version = \"1.0.0\""
        ].join("\n"),
        "utf8"
      );
      writeFileSync(path.join(projectRoot, "LICENSE"), "workspace license", "utf8");
      writeFileSync(path.join(memberRoot, "LICENSE"), "member license", "utf8");
      writeFileSync(
        path.join(projectRoot, "Cargo.lock"),
        [
          "[[package]]",
          "name = \"member\"",
          "version = \"1.0.0\""
        ].join("\n"),
        "utf8"
      );

      const result = parseCargoLockfile(path.join(projectRoot, "Cargo.lock"));

      expect(result.ok).toBe(true);
      if (!result.ok) {
        throw new Error(result.error.message);
      }
      expect(result.value.embeddedEvidence?.[0]?.files).toEqual([{
        path: "LICENSE",
        kind: "license",
        text: "member license"
      }]);
    } finally {
      rmSync(projectRoot, { recursive: true, force: true });
    }
  });

  test("reads implicit workspace members from root path dependencies", () => {
    const projectRoot = mkdtempSync(path.join(tmpdir(), "ohrisk-cargo-implicit-workspace-"));
    const implicitRoot = path.join(projectRoot, "crates", "implicit");
    const excludedRoot = path.join(projectRoot, "crates", "excluded");

    try {
      mkdirSync(implicitRoot, { recursive: true });
      mkdirSync(excludedRoot, { recursive: true });
      writeFileSync(
        path.join(projectRoot, "Cargo.toml"),
        [
          "[workspace]",
          "members = []",
          "exclude = [\"crates/excluded\"]",
          "",
          "[workspace.package]",
          "version = \"1.0.0\"",
          "license = \"MIT\"",
          "",
          "[workspace.dependencies]",
          "implicit = { path = \"crates/implicit\" }",
          "excluded = { path = \"crates/excluded\" }",
          "",
          "[package]",
          "name = \"workspace-root\"",
          "version = \"1.0.0\"",
          "",
          "[dependencies]",
          "implicit.workspace = true",
          "excluded.workspace = true"
        ].join("\n"),
        "utf8"
      );
      for (const [root, name] of [[implicitRoot, "implicit"], [excludedRoot, "excluded"]] as const) {
        writeFileSync(
          path.join(root, "Cargo.toml"),
          [
            "[package]",
            `name = "${name}"`,
            "version.workspace = true",
            "license.workspace = true"
          ].join("\n"),
          "utf8"
        );
      }
      writeFileSync(
        path.join(projectRoot, "Cargo.lock"),
        [
          "[[package]]",
          "name = \"implicit\"",
          "version = \"1.0.0\"",
          "",
          "[[package]]",
          "name = \"excluded\"",
          "version = \"1.0.0\""
        ].join("\n"),
        "utf8"
      );

      const result = parseCargoLockfile(path.join(projectRoot, "Cargo.lock"));

      expect(result.ok).toBe(true);
      if (!result.ok) {
        throw new Error(result.error.message);
      }
      expect(result.value.embeddedEvidence).toEqual([{
        packageId: "implicit@1.0.0",
        metadataLicense: "MIT",
        metadataSource: "workspace Cargo.toml",
        files: [],
        source: "local",
        warnings: []
      }]);
    } finally {
      rmSync(projectRoot, { recursive: true, force: true });
    }
  });

  test("selects implicit path members from a repository inventory", () => {
    const projectRoot = path.resolve("workspace");
    const paths = findCargoWorkspaceMemberManifestPathsFromRelativePaths({
      rootManifestText: [
        "[workspace]",
        "members = []",
        "exclude = [\"crates/excluded\"]",
        "",
        "[workspace.dependencies]",
        "implicit = { path = \"crates/implicit\" }",
        "excluded = { path = \"crates/excluded\" }"
      ].join("\n"),
      lockfilePath: path.join(projectRoot, "Cargo.lock"),
      projectRoot,
      relativePaths: [
        "Cargo.toml",
        "crates/implicit/Cargo.toml",
        "crates/excluded/Cargo.toml",
        "crates/unrelated/Cargo.toml"
      ]
    });

    expect(paths.map((item) => item.relativeManifestPath)).toEqual([
      "crates/implicit/Cargo.toml"
    ]);
  });

  test("reads one-segment wildcard Cargo workspace member manifests and honors excludes", () => {
    const projectRoot = mkdtempSync(path.join(tmpdir(), "ohrisk-cargo-workspace-wildcard-"));
    const appRoot = path.join(projectRoot, "crates", "app");
    const emptyRoot = path.join(projectRoot, "crates", "empty");
    const ignoredRoot = path.join(projectRoot, "crates", "ignored");

    try {
      mkdirSync(appRoot, { recursive: true });
      mkdirSync(emptyRoot, { recursive: true });
      mkdirSync(ignoredRoot, { recursive: true });
      writeFileSync(
        path.join(projectRoot, "Cargo.toml"),
        [
          "[workspace]",
          "members = [\"crates/*\"]",
          "exclude = [\"crates/ignored\"]"
        ].join("\n"),
        "utf8"
      );
      writeFileSync(
        path.join(appRoot, "Cargo.toml"),
        [
          "[package]",
          "name = \"app\"",
          "version = \"0.1.0\"",
          "",
          "[dependencies]",
          "workspace-risk = \"1\""
        ].join("\n"),
        "utf8"
      );
      writeFileSync(
        path.join(ignoredRoot, "Cargo.toml"),
        [
          "[package]",
          "name = \"ignored\"",
          "version = \"0.1.0\"",
          "",
          "[dependencies]",
          "ignored-risk = \"1\""
        ].join("\n"),
        "utf8"
      );
      writeFileSync(
        path.join(projectRoot, "Cargo.lock"),
        [
          "[[package]]",
          "name = \"workspace-risk\"",
          "version = \"1.0.0\"",
          "",
          "[[package]]",
          "name = \"ignored-risk\"",
          "version = \"1.0.0\""
        ].join("\n"),
        "utf8"
      );

      const result = parseCargoLockfile(path.join(projectRoot, "Cargo.lock"));

      expect(result.ok).toBe(true);
      if (!result.ok) {
        throw new Error(result.error.message);
      }

      expect(result.value.nodes).toHaveLength(1);
      expect(result.value.nodes[0]).toMatchObject({
        id: "workspace-risk@1.0.0",
        dependencyType: "production",
        direct: true
      });
    } finally {
      rmSync(projectRoot, { recursive: true, force: true });
    }
  });

  test("reads nested wildcard Cargo workspace member manifests", () => {
    const projectRoot = mkdtempSync(path.join(tmpdir(), "ohrisk-cargo-workspace-nested-wildcard-"));
    const pluginRoot = path.join(projectRoot, "crates", "group-a", "plugins", "risk-plugin");
    const ignoredRoot = path.join(projectRoot, "crates", "group-b", "plugins", "ignored-plugin");

    try {
      mkdirSync(pluginRoot, { recursive: true });
      mkdirSync(ignoredRoot, { recursive: true });
      writeFileSync(
        path.join(projectRoot, "Cargo.toml"),
        [
          "[workspace]",
          "members = [\"crates/*/plugins/*\"]",
          "exclude = [\"crates/group-b/plugins/*\"]"
        ].join("\n"),
        "utf8"
      );
      writeFileSync(
        path.join(pluginRoot, "Cargo.toml"),
        [
          "[package]",
          "name = \"risk-plugin\"",
          "version = \"0.1.0\"",
          "",
          "[dependencies]",
          "nested-risk = \"1\""
        ].join("\n"),
        "utf8"
      );
      writeFileSync(
        path.join(ignoredRoot, "Cargo.toml"),
        [
          "[package]",
          "name = \"ignored-plugin\"",
          "version = \"0.1.0\"",
          "",
          "[dependencies]",
          "ignored-risk = \"1\""
        ].join("\n"),
        "utf8"
      );
      writeFileSync(
        path.join(projectRoot, "Cargo.lock"),
        [
          "[[package]]",
          "name = \"nested-risk\"",
          "version = \"1.0.0\"",
          "",
          "[[package]]",
          "name = \"ignored-risk\"",
          "version = \"1.0.0\""
        ].join("\n"),
        "utf8"
      );

      const result = parseCargoLockfile(path.join(projectRoot, "Cargo.lock"));

      expect(result.ok).toBe(true);
      if (!result.ok) {
        throw new Error(result.error.message);
      }

      expect(result.value.nodes).toHaveLength(1);
      expect(result.value.nodes[0]).toMatchObject({
        id: "nested-risk@1.0.0",
        dependencyType: "production",
        direct: true
      });
    } finally {
      rmSync(projectRoot, { recursive: true, force: true });
    }
  });

  test("reads segment star and question Cargo workspace member patterns and honors excludes", () => {
    const projectRoot = mkdtempSync(path.join(tmpdir(), "ohrisk-cargo-workspace-partial-glob-"));
    const appRoot = path.join(projectRoot, "crates", "app-core");
    const ignoredRoot = path.join(projectRoot, "crates", "app-ignore");
    const ignoredByPatternRoot = path.join(projectRoot, "crates", "app-ignored-core");
    const cliRoot = path.join(projectRoot, "tools", "cli");

    try {
      mkdirSync(appRoot, { recursive: true });
      mkdirSync(ignoredRoot, { recursive: true });
      mkdirSync(ignoredByPatternRoot, { recursive: true });
      mkdirSync(cliRoot, { recursive: true });
      writeFileSync(
        path.join(projectRoot, "Cargo.toml"),
        [
          "[workspace]",
          "members = [\"crates/app-*\", \"tools/?li\"]",
          "exclude = [\"crates/app-ignore\", \"crates/app-ignored-*\"]"
        ].join("\n"),
        "utf8"
      );
      writeFileSync(
        path.join(appRoot, "Cargo.toml"),
        [
          "[package]",
          "name = \"app-core\"",
          "version = \"0.1.0\"",
          "",
          "[dependencies]",
          "partial-glob-risk = \"1\""
        ].join("\n"),
        "utf8"
      );
      writeFileSync(
        path.join(ignoredRoot, "Cargo.toml"),
        [
          "[package]",
          "name = \"app-ignore\"",
          "version = \"0.1.0\"",
          "",
          "[dependencies]",
          "ignored-risk = \"1\""
        ].join("\n"),
        "utf8"
      );
      writeFileSync(
        path.join(ignoredByPatternRoot, "Cargo.toml"),
        [
          "[package]",
          "name = \"app-ignored-core\"",
          "version = \"0.1.0\"",
          "",
          "[dependencies]",
          "pattern-ignored-risk = \"1\""
        ].join("\n"),
        "utf8"
      );
      writeFileSync(
        path.join(cliRoot, "Cargo.toml"),
        [
          "[package]",
          "name = \"cli\"",
          "version = \"0.1.0\"",
          "",
          "[dependencies]",
          "question-glob-risk = \"1\""
        ].join("\n"),
        "utf8"
      );
      writeFileSync(
        path.join(projectRoot, "Cargo.lock"),
        [
          "[[package]]",
          "name = \"partial-glob-risk\"",
          "version = \"1.0.0\"",
          "",
          "[[package]]",
          "name = \"question-glob-risk\"",
          "version = \"1.0.0\"",
          "",
          "[[package]]",
          "name = \"pattern-ignored-risk\"",
          "version = \"1.0.0\"",
          "",
          "[[package]]",
          "name = \"ignored-risk\"",
          "version = \"1.0.0\""
        ].join("\n"),
        "utf8"
      );

      const result = parseCargoLockfile(path.join(projectRoot, "Cargo.lock"));

      expect(result.ok).toBe(true);
      if (!result.ok) {
        throw new Error(result.error.message);
      }

      expect(result.value.nodes.map((node) => node.id)).toEqual([
        "partial-glob-risk@1.0.0",
        "question-glob-risk@1.0.0"
      ]);
    } finally {
      rmSync(projectRoot, { recursive: true, force: true });
    }
  });

  test("uses package aliases from Cargo.toml when resolving lockfile records", () => {
    const result = parseCargoLockText(
      [
        "[[package]]",
        "name = \"actual-crate\"",
        "version = \"1.0.0\""
      ].join("\n"),
      "Cargo.lock",
      {
        manifestText: [
          "[package]",
          "name = \"fixture-rust\"",
          "",
          "[dependencies]",
          "alias_crate = { package = \"actual-crate\", version = \"1\" }"
        ].join("\n")
      }
    );

    expect(result.ok).toBe(true);
    if (!result.ok) {
      throw new Error(result.error.message);
    }

    expect(result.value.nodes.map((node) => node.id)).toEqual(["actual-crate@1.0.0"]);
    expect(result.value.nodes[0]?.direct).toBe(true);
  });

  test("uses root lockfile dependency versions when the same crate appears more than once", () => {
    const cargoLock = [
      "[[package]]",
      "name = \"fixture-rust\"",
      "version = \"0.1.0\"",
      "dependencies = [",
      " \"shared-crate 2.0.0\",",
      "]",
      "",
      "[[package]]",
      "name = \"shared-crate\"",
      "version = \"1.0.0\"",
      "",
      "[[package]]",
      "name = \"shared-crate\"",
      "version = \"2.0.0\""
    ].join("\n");
    const cargoToml = [
      "[package]",
      "name = \"fixture-rust\"",
      "version = \"0.1.0\"",
      "",
      "[dependencies]",
      "shared-crate = \"2\""
    ].join("\n");

    const result = parseCargoLockText(cargoLock, "fixture-rust/Cargo.lock", {
      manifestText: cargoToml
    });

    expect(result.ok).toBe(true);
    if (!result.ok) {
      throw new Error(result.error.message);
    }

    expect(result.value.nodes.map((node) => node.id)).toEqual(["shared-crate@2.0.0"]);
    expect(result.value.nodes[0]?.paths).toEqual([["fixture-rust", "shared-crate@2.0.0"]]);
  });

  test("reports malformed package records as typed errors", () => {
    const result = parseCargoLockText(
      [
        "[[package]]",
        "name = \"missing-version\""
      ].join("\n"),
      "Cargo.lock"
    );

    expect(result.ok).toBe(false);
    if (result.ok) {
      throw new Error("Expected malformed Cargo.lock to fail.");
    }

    expect(result.error.code).toBe("CARGO_LOCK_PARSE_FAILED");
  });
});
