import { type HtmlReportText } from "./html-report-text";

export function renderHtmlFilterScript(text: HtmlReportText): string[] {
  const filterMessages = JSON.stringify({
    status: text.messages.filterStatusTemplate,
    expandFallback: text.messages.defaultExpandLabel,
    collapseFallback: text.messages.defaultCollapseLabel,
    collapseText: text.messages.collapseText
  });

  return [
    "(() => {",
    `  const messages = ${filterMessages};`,
    "  const severityFilters = Array.from(document.querySelectorAll('[data-finding-filter]'));",
    "  const cards = Array.from(document.querySelectorAll('[data-finding-card]'));",
    "  const searchInput = document.querySelector('[data-finding-search]');",
    "  const dependencyFilter = document.querySelector('[data-finding-dependency-filter]');",
    "  const actionFilter = document.querySelector('[data-finding-action-filter]');",
    "  const status = document.querySelector('[data-finding-filter-status]');",
    "  const empty = document.querySelector('[data-finding-filter-empty]');",
    "  const inspector = document.querySelector('[data-finding-inspector]');",
    "  const searchTexts = new Map(cards.map((card) => [card, (card.textContent || '').replace(/\\s+/g, ' ').toLowerCase()]));",
    "  const fingerprintData = document.querySelector('#ohrisk-fingerprint-data');",
    "  let fingerprintPayload = { s: [], f: [] };",
    "  if (fingerprintData) {",
    "    try {",
    "      const parsed = JSON.parse(fingerprintData.textContent || '[]');",
    "      if (parsed && parsed.v === 2 && Array.isArray(parsed.s) && Array.isArray(parsed.f)) {",
    "        fingerprintPayload = parsed;",
    "      }",
    "    } catch {",
    "      fingerprintPayload = { s: [], f: [] };",
    "    }",
    "  }",
    "  const decodePaths = (encodedPaths) => {",
    "    if (!Array.isArray(encodedPaths)) return null;",
    "    const paths = [];",
    "    let previous = [];",
    "    for (const encodedPath of encodedPaths) {",
    "      if (!Array.isArray(encodedPath) || encodedPath.length === 0) return null;",
    "      const shared = encodedPath[0];",
    "      if (!Number.isInteger(shared) || shared < 0 || shared > previous.length) return null;",
    "      const path = previous.slice(0, shared);",
    "      for (const stringIndex of encodedPath.slice(1)) {",
    "        const segment = fingerprintPayload.s[stringIndex];",
    "        if (typeof segment !== 'string') return null;",
    "        path.push(segment);",
    "      }",
    "      paths.push(path);",
    "      previous = path;",
    "    }",
    "    return paths;",
    "  };",
    "  const encodeFindingComponent = (value) => String(value).replace(/%/g, '%25').replace(/:/g, '%3A').replace(/>/g, '%3E').replace(/\\|/g, '%7C');",
    "  const decodeFingerprint = (fingerprintIndex) => {",
    "    const record = fingerprintPayload.f[fingerprintIndex];",
    "    if (typeof record === 'string') {",
    "      return record;",
    "    }",
    "    if (!Array.isArray(record) || (record.length !== 5 && record.length !== 8)) {",
    "      return null;",
    "    }",
    "    const packageId = fingerprintPayload.s[record[0]];",
    "    if (typeof packageId !== 'string' || !Array.isArray(record[3])) {",
    "      return null;",
    "    }",
    "    const paths = decodePaths(record[3]);",
    "    if (!paths) return null;",
    "    const findingId = [",
    "      encodeFindingComponent(packageId),",
    "      encodeFindingComponent(record[1]),",
    "      encodeFindingComponent(record[2]),",
    "      paths.map((path) => path.map(encodeFindingComponent).join('>')).join('|')",
    "    ].join('::');",
    "    if (record.length === 5) {",
    "      const suffix = fingerprintPayload.s[record[4]];",
    "      return typeof suffix === 'string' ? `${findingId}::${suffix}` : null;",
    "    }",
    "    const reason = fingerprintPayload.s[record[6]];",
    "    const evidence = record[7].map((stringIndex) => fingerprintPayload.s[stringIndex]);",
    "    if (typeof reason !== 'string' || evidence.some((item) => typeof item !== 'string')) {",
    "      return null;",
    "    }",
    "    return [",
    "      findingId,",
    "      encodeFindingComponent(record[4]),",
    "      encodeFindingComponent(record[5]),",
    "      encodeFindingComponent(reason),",
    "      evidence.map(encodeFindingComponent).join('|')",
    "    ].join('::');",
    "  };",
    "",
    "  const selectFinding = (card, focusInspector = false) => {",
    "    const details = card?.querySelector('[data-finding-details]');",
    "    if (!card || !details || !inspector) return;",
    "    for (const candidate of cards) {",
    "      const selected = candidate === card;",
    "      candidate.classList.toggle('is-selected', selected);",
    "      const button = candidate.querySelector('[data-finding-select]');",
    "      if (button) button.setAttribute('aria-pressed', String(selected));",
    "    }",
    "    inspector.replaceChildren(details.cloneNode(true));",
    "    const inspectorDetails = inspector.querySelector('[data-finding-details]');",
    "    inspectorDetails?.classList.remove('finding-details-source');",
    "    for (const element of inspector.querySelectorAll('[id]')) element.removeAttribute('id');",
    "    for (const element of inspector.querySelectorAll('[aria-controls]')) element.removeAttribute('aria-controls');",
    "    for (const content of inspector.querySelectorAll('[data-collapsible-content]')) {",
    "      content.classList.toggle('is-collapsed', false);",
    "      const deferredFingerprint = content.querySelector('[data-fingerprint-index]');",
    "      if (deferredFingerprint) {",
    "        const fingerprintIndex = Number.parseInt(deferredFingerprint.dataset.fingerprintIndex || '', 10);",
    "        const fingerprint = decodeFingerprint(fingerprintIndex);",
    "        if (typeof fingerprint === 'string') deferredFingerprint.textContent = fingerprint;",
    "      }",
    "    }",
    "    for (const toggle of inspector.querySelectorAll('[data-collapsible-toggle]')) toggle.hidden = true;",
    "    if (focusInspector && window.matchMedia('(max-width: 900px)').matches) inspector.focus();",
    "  };",
    "",
    "  const updateFindings = () => {",
    "    const selectedSeverities = new Set(severityFilters.filter((filter) => filter.checked).map((filter) => filter.value));",
    "    const searchText = (searchInput?.value || '').trim().toLowerCase();",
    "    const dependencyScope = dependencyFilter?.value || 'all';",
    "    const recommendation = actionFilter?.value || 'all';",
    "    let visibleCount = 0;",
    "",
    "    for (const card of cards) {",
    "      const severityMatches = selectedSeverities.has(card.dataset.severity || '');",
    "      const dependencyMatches = dependencyScope === 'all' || card.dataset.dependencyScope === dependencyScope;",
    "      const recommendationMatches = recommendation === 'all' || card.dataset.recommendation === recommendation;",
    "      const searchMatches = searchText === '' || (searchTexts.get(card) || '').includes(searchText);",
    "      const visible = severityMatches && dependencyMatches && recommendationMatches && searchMatches;",
    "      card.hidden = !visible;",
    "      if (visible) {",
    "        visibleCount += 1;",
    "      }",
    "    }",
    "",
    "    if (status) {",
    "      status.textContent = messages.status.replace('{visible}', String(visibleCount)).replace('{total}', String(cards.length));",
    "    }",
    "",
    "    if (empty) {",
    "      empty.hidden = visibleCount !== 0;",
    "    }",
    "    const selectedCard = cards.find((card) => card.classList.contains('is-selected') && !card.hidden);",
    "    if (!selectedCard) selectFinding(cards.find((card) => !card.hidden));",
    "",
    "    refreshVisibleCollapsibles();",
    "  };",
    "",
    "  for (const filter of severityFilters) {",
    "    filter.addEventListener('change', updateFindings);",
    "  }",
    "  searchInput?.addEventListener('input', updateFindings);",
    "  dependencyFilter?.addEventListener('change', updateFindings);",
    "  actionFilter?.addEventListener('change', updateFindings);",
    "  for (const card of cards) {",
    "    card.querySelector('[data-finding-select]')?.addEventListener('click', () => selectFinding(card, true));",
    "  }",
    "",
    "  const getCollapsedHeight = (content) => {",
    "    const styles = window.getComputedStyle(content);",
    "    const lineHeight = Number.parseFloat(styles.lineHeight);",
    "    return Number.isFinite(lineHeight) && lineHeight > 0 ? lineHeight * 3 : 0;",
    "  };",
    "",
    "  const isCollapsibleOverflowing = (content) => {",
    "    const width = content.getBoundingClientRect().width;",
    "    const collapsedHeight = getCollapsedHeight(content);",
    "    if (width <= 0 || collapsedHeight <= 0 || !content.parentElement) {",
    "      return null;",
    "    }",
    "    if (content.scrollHeight > content.clientHeight + 1) {",
    "      return true;",
    "    }",
    "",
    "    const clone = content.cloneNode(true);",
    "    clone.classList.remove('is-collapsed');",
    "    clone.removeAttribute('data-collapsible-content');",
    "    clone.setAttribute('aria-hidden', 'true');",
    "    clone.style.position = 'absolute';",
    "    clone.style.visibility = 'hidden';",
    "    clone.style.pointerEvents = 'none';",
    "    clone.style.width = `${width}px`;",
    "    clone.style.maxHeight = 'none';",
    "    clone.style.display = 'block';",
    "    clone.style.overflow = 'visible';",
    "    clone.style.webkitLineClamp = 'unset';",
    "    clone.style.webkitBoxOrient = 'unset';",
    "    content.parentElement.appendChild(clone);",
    "    const expandedHeight = clone.scrollHeight;",
    "    clone.remove();",
    "    return expandedHeight > collapsedHeight + 1;",
    "  };",
    "",
    "  const refreshCollapsible = (container) => {",
    "    const content = container.querySelector('[data-collapsible-content]');",
    "    const toggle = container.querySelector('[data-collapsible-toggle]');",
    "    if (!content || !toggle) {",
    "      return;",
    "    }",
    "    const overflowed = content.querySelector('[data-fingerprint-index]') ? true : isCollapsibleOverflowing(content);",
    "    if (overflowed === null) {",
    "      return;",
    "    }",
    "    toggle.hidden = !overflowed;",
    "    if (!overflowed) {",
    "      toggle.setAttribute('aria-expanded', 'false');",
    "      toggle.setAttribute('aria-label', toggle.dataset.expandLabel || messages.expandFallback);",
    "      toggle.textContent = '...';",
    "      content.classList.add('is-collapsed');",
    "    }",
    "  };",
    "",
    "  let visibleCollapsibleRefreshScheduled = false;",
    "  const refreshVisibleCollapsibles = () => {",
    "    if (visibleCollapsibleRefreshScheduled) {",
    "      return;",
    "    }",
    "    visibleCollapsibleRefreshScheduled = true;",
    "    requestAnimationFrame(() => {",
    "      visibleCollapsibleRefreshScheduled = false;",
    "      for (const container of collapsibles) {",
    "        const card = container.closest('[data-finding-card]');",
    "        if (card && !card.hidden) {",
    "          refreshCollapsible(container);",
    "        }",
    "      }",
    "    });",
    "  };",
    "",
    "  const collapsibles = Array.from(document.querySelectorAll('[data-collapsible]'));",
    "  for (const container of collapsibles) {",
    "    const content = container.querySelector('[data-collapsible-content]');",
    "    const toggle = container.querySelector('[data-collapsible-toggle]');",
    "    if (!content || !toggle) {",
    "      continue;",
    "    }",
    "    toggle.addEventListener('click', () => {",
    "      const expanded = toggle.getAttribute('aria-expanded') === 'true';",
    "      const nextExpanded = !expanded;",
    "      const deferredFingerprint = content.querySelector('[data-fingerprint-index]');",
    "      if (nextExpanded && deferredFingerprint) {",
    "        const fingerprintIndex = Number.parseInt(deferredFingerprint.dataset.fingerprintIndex || '', 10);",
    "        const fingerprint = decodeFingerprint(fingerprintIndex);",
    "        if (typeof fingerprint === 'string') {",
    "          deferredFingerprint.textContent = fingerprint;",
    "          deferredFingerprint.removeAttribute('data-fingerprint-index');",
    "        }",
    "      }",
    "      toggle.setAttribute('aria-expanded', String(nextExpanded));",
    "      toggle.setAttribute('aria-label', nextExpanded ? toggle.dataset.collapseLabel || messages.collapseFallback : toggle.dataset.expandLabel || messages.expandFallback);",
    "      toggle.textContent = nextExpanded ? messages.collapseText : '...';",
    "      content.classList.toggle('is-collapsed', !nextExpanded);",
    "    });",
    "  }",
    "",
    "  refreshVisibleCollapsibles();",
    "  window.addEventListener('resize', () => {",
    "    refreshVisibleCollapsibles();",
    "  });",
    "",
    "  selectFinding(cards[0]);",
    "  updateFindings();",
    "})();"
  ];
}
