export type OhriskErrorCategory =
  | "invalid_input"
  | "unsupported_input"
  | "filesystem"
  | "network"
  | "internal";

export type OhriskErrorCode =
  | "INVALID_ARGUMENT"
  | "UNSUPPORTED_COMMAND"
  | "NO_SUPPORTED_LOCKFILE"
  | "MULTIPLE_LOCKFILES"
  | "LOCKFILE_NOT_FOUND"
  | "LOCKFILE_NOT_FILE"
  | "UNSUPPORTED_LOCKFILE"
  | "PROJECT_DISCOVERY_FAILED"
  | "BUN_LOCK_READ_FAILED"
  | "BUN_LOCK_PARSE_FAILED"
  | "PACKAGE_LOCK_READ_FAILED"
  | "PACKAGE_LOCK_PARSE_FAILED"
  | "PNPM_LOCK_READ_FAILED"
  | "PNPM_LOCK_PARSE_FAILED"
  | "PNPM_WORKSPACE_READ_FAILED"
  | "PNPM_WORKSPACE_PARSE_FAILED"
  | "DENO_LOCK_READ_FAILED"
  | "DENO_LOCK_PARSE_FAILED"
  | "CARGO_LOCK_READ_FAILED"
  | "CARGO_LOCK_PARSE_FAILED"
  | "CARGO_MANIFEST_READ_FAILED"
  | "GO_MOD_READ_FAILED"
  | "GO_MOD_PARSE_FAILED"
  | "GO_SUM_READ_FAILED"
  | "GO_WORK_READ_FAILED"
  | "GO_WORK_PARSE_FAILED"
  | "GO_WORK_MODULE_READ_FAILED"
  | "GO_WORK_SUM_READ_FAILED"
  | "POETRY_LOCK_READ_FAILED"
  | "POETRY_LOCK_PARSE_FAILED"
  | "PYPROJECT_READ_FAILED"
  | "PIPFILE_LOCK_READ_FAILED"
  | "PIPFILE_LOCK_PARSE_FAILED"
  | "PDM_LOCK_READ_FAILED"
  | "PDM_LOCK_PARSE_FAILED"
  | "REQUIREMENTS_READ_FAILED"
  | "REQUIREMENTS_PARSE_FAILED"
  | "UV_LOCK_READ_FAILED"
  | "UV_LOCK_PARSE_FAILED"
  | "PYLOCK_READ_FAILED"
  | "PYLOCK_PARSE_FAILED"
  | "GRADLE_LOCK_READ_FAILED"
  | "GRADLE_LOCK_PARSE_FAILED"
  | "GRADLE_VERSION_CATALOG_READ_FAILED"
  | "GRADLE_VERSION_CATALOG_PARSE_FAILED"
  | "BAZEL_MODULE_READ_FAILED"
  | "BAZEL_MODULE_PARSE_FAILED"
  | "MAVEN_POM_READ_FAILED"
  | "MAVEN_POM_PARSE_FAILED"
  | "NUGET_LOCK_READ_FAILED"
  | "NUGET_LOCK_PARSE_FAILED"
  | "NUGET_ASSETS_READ_FAILED"
  | "NUGET_ASSETS_PARSE_FAILED"
  | "DOTNET_PROJECT_READ_FAILED"
  | "DOTNET_PROJECT_PARSE_FAILED"
  | "NUGET_PACKAGES_CONFIG_READ_FAILED"
  | "NUGET_PACKAGES_CONFIG_PARSE_FAILED"
  | "CONAN_LOCK_READ_FAILED"
  | "CONAN_LOCK_PARSE_FAILED"
  | "CONDA_ENVIRONMENT_READ_FAILED"
  | "CONDA_ENVIRONMENT_PARSE_FAILED"
  | "CONDA_LOCK_READ_FAILED"
  | "CONDA_LOCK_PARSE_FAILED"
  | "VCPKG_JSON_READ_FAILED"
  | "VCPKG_JSON_PARSE_FAILED"
  | "VCPKG_STATUS_READ_FAILED"
  | "VCPKG_STATUS_PARSE_FAILED"
  | "TERRAFORM_LOCK_READ_FAILED"
  | "TERRAFORM_LOCK_PARSE_FAILED"
  | "HELM_CHART_READ_FAILED"
  | "HELM_CHART_PARSE_FAILED"
  | "NIX_FLAKE_LOCK_READ_FAILED"
  | "NIX_FLAKE_LOCK_PARSE_FAILED"
  | "UNITY_PACKAGES_LOCK_READ_FAILED"
  | "UNITY_PACKAGES_LOCK_PARSE_FAILED"
  | "RENV_LOCK_READ_FAILED"
  | "RENV_LOCK_PARSE_FAILED"
  | "JULIA_MANIFEST_READ_FAILED"
  | "JULIA_MANIFEST_PARSE_FAILED"
  | "STACK_LOCK_READ_FAILED"
  | "STACK_LOCK_PARSE_FAILED"
  | "CPANFILE_SNAPSHOT_READ_FAILED"
  | "CPANFILE_SNAPSHOT_PARSE_FAILED"
  | "LUAROCKS_LOCK_READ_FAILED"
  | "LUAROCKS_LOCK_PARSE_FAILED"
  | "PUBSPEC_LOCK_READ_FAILED"
  | "PUBSPEC_LOCK_PARSE_FAILED"
  | "SWIFT_PACKAGE_RESOLVED_READ_FAILED"
  | "SWIFT_PACKAGE_RESOLVED_PARSE_FAILED"
  | "CARTFILE_RESOLVED_READ_FAILED"
  | "CARTFILE_RESOLVED_PARSE_FAILED"
  | "PODFILE_LOCK_READ_FAILED"
  | "PODFILE_LOCK_PARSE_FAILED"
  | "MIX_LOCK_READ_FAILED"
  | "MIX_LOCK_PARSE_FAILED"
  | "REBAR_LOCK_READ_FAILED"
  | "REBAR_LOCK_PARSE_FAILED"
  | "GEMFILE_LOCK_READ_FAILED"
  | "GEMFILE_LOCK_PARSE_FAILED"
  | "COMPOSER_LOCK_READ_FAILED"
  | "COMPOSER_LOCK_PARSE_FAILED"
  | "COMPOSER_JSON_READ_FAILED"
  | "CYCLONEDX_READ_FAILED"
  | "CYCLONEDX_PARSE_FAILED"
  | "SPDX_READ_FAILED"
  | "SPDX_PARSE_FAILED"
  | "YARN_LOCK_READ_FAILED"
  | "YARN_LOCK_PARSE_FAILED"
  | "YARN_PACKAGE_JSON_READ_FAILED"
  | "YARN_PACKAGE_JSON_PARSE_FAILED"
  | "YARN_WORKSPACE_PACKAGE_JSON_READ_FAILED"
  | "GIT_REF_FILE_NOT_FOUND"
  | "GIT_REF_READ_FAILED"
  | "GIT_REF_PATH_OUTSIDE_PROJECT"
  | "REPORT_WRITE_FAILED"
  | "PACKAGE_EVIDENCE_READ_FAILED"
  | "PACKAGE_JSON_PARSE_FAILED"
  | "PACKAGE_INTEGRITY_CHECK_FAILED"
  | "WAIVER_FILE_READ_FAILED"
  | "WAIVER_FILE_PARSE_FAILED"
  | "TARBALL_PARSE_FAILED"
  | "REGISTRY_METADATA_FETCH_FAILED"
  | "TARBALL_FETCH_FAILED";

export type OhriskError = {
  code: OhriskErrorCode;
  category: OhriskErrorCategory;
  message: string;
  details?: Record<string, unknown>;
};

export function createError(error: OhriskError): OhriskError {
  return error;
}

export function exitCodeForError(error: OhriskError): number {
  switch (error.category) {
    case "invalid_input":
    case "unsupported_input":
      return 2;
    case "filesystem":
    case "network":
    case "internal":
      return 1;
  }
}

export function formatError(error: OhriskError): string {
  const lines = [
    "Ohrisk could not complete the command.",
    `${error.code}: ${error.message}`
  ];

  if (error.details) {
    for (const [key, value] of Object.entries(error.details)) {
      lines.push(`${key}: ${formatDetail(value)}`);
    }
  }

  return lines.join("\n");
}

function formatDetail(value: unknown): string {
  if (Array.isArray(value)) {
    return value.length === 0 ? "none" : value.join(", ");
  }

  if (typeof value === "string") {
    return value;
  }

  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }

  if (value === null || value === undefined) {
    return "none";
  }

  return JSON.stringify(value);
}
